#!/bin/bash 
#SBATCH --time=96:00:00
#SBATCH -p gpu
#SBATCH -n 1
#SBATCH -e err-cristobal."%j".txt
#SBATCH -o out-cristobal."%j".txt
#SBATCH -J CrisCL
#SBATCH --mem=64g
#SBATCH --gres=gpu:a40:1
#SBATCH --nodelist=node201


#module load cuda/12.2

# Activate Conda environment properly
source ~/.bashrc
conda activate cl_env

# export PATH=/home/cmestre/miniconda3/envs/cl_env/bin:$PATH

cd /home/cmestre/tsvd
pwd  # Print current directory for debugging

# executable 
#/usr/bin/sleep 5m
# pwd


# Load any required modules

# Run your Python script with command-line parameters
# python my_script.py $ARG1

if [ -z "$CONFIG_ARG" ]; then
    CONFIG_ARG="./exps/ranpac_ease/adapter_cifar_in21k.json"
fi

python main.py $CONFIG_ARG
